# Generated by Django 5.2.6 on 2025-10-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chat_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название чата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Чат',
                'verbose_name_plural': 'AI Чаты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'Пользователь'), ('ai', 'ИИ')], max_length=10, verbose_name='Отправитель')),
                ('content', models.TextField(verbose_name='Содержимое сообщения')),
                ('original_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Исходный язык')),
                ('translated_content', models.TextField(blank=True, null=True, verbose_name='Переведенное содержимое')),
                ('translation_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Язык перевода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель ИИ')),
                ('ai_prompt_used', models.TextField(blank=True, null=True, verbose_name='Использованный промпт')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время ответа (мс)')),
                ('ai_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to='users.aichat')),
            ],
            options={
                'verbose_name': 'AI Сообщение',
                'verbose_name_plural': 'AI Сообщения',
                'ordering': ['created_at'],
            },
        ),
    ]
